### ISSUE TITLE
FusionCharts XT installation Not Working 

### ISSUE THREAD

**Issue by flatrixnet** [xpandit/pentaho-fc-plugin#178]
After the installation of the key when the user tries to upload the zip with fusioncharts nothing happens. 
The Charts are not installed

**Comment by danielams** [comment]
Added new kettle transformation to handle with more than one fusion xt tree structure.
For new folder structures add the following property in the fusionCharts.properties file.

xt_folder=${folder where the js file are in}

For add more than one, separate them by comma.
