### ISSUE TITLE
Legacy Dashboard | Warning wrong font

### ISSUE THREAD

**Issue by tiagorodriguessimoes** [xpandit/pentaho-fc-plugin#187]
When we don't have XT suite installed the warning should have this font:
✅
![puc-fusion-data_cdf-good-font](https://user-images.githubusercontent.com/10504105/32217671-a93f4154-be20-11e7-8364-263d2d5af3dc.PNG)
 
Instead of:
❌
![puc-fusion-dashboard_xpfusionchartcomponent-bad-font](https://user-images.githubusercontent.com/10504105/32217689-b6608db6-be20-11e7-9369-a42ba355a25c.PNG)

**Comment by joaotsilv** [comment]
The font was updated in the new samples because it now uses bootstrap css properties instead of pentaho-cdf. Updated dashboard csss so they are similar. (da46c60)
