### ISSUE TITLE
call verifyKey repeated when loading a dashboard

### ISSUE THREAD

**Issue by tiagorodriguessimoes** [xpandit/pentaho-fc-plugin#188]
When loading a dashboar _verifyKey_ is called everytime before executing an instruction/query.

![verifyrepeated](https://user-images.githubusercontent.com/10504105/32370520-4e266042-c085-11e7-88a6-9e996d5c55e2.PNG)

It should verify only once at start and cache it

**Comment by joaotsilv** [comment]
This is resolved :clap:
